Repository aquelemiguel/parrot, pull requests merged in 2022-01, with the labels that each got.

#64 refactor: commands
  src/commands/clear.rs
  src/commands/genius/explain.rs
  src/commands/genius/lyrics.rs
  src/commands/leave.rs
  src/commands/now_playing.rs
  src/commands/pause.rs
  src/commands/play.rs
  src/commands/playtop.rs
  src/commands/queue.rs
  src/commands/remove.rs
  src/commands/repeat.rs
  src/commands/resume.rs
  src/commands/seek.rs
  src/commands/shuffle.rs
  src/commands/skip.rs
  src/commands/stop.rs
  src/commands/summon.rs
  src/events/idle_notifier.rs
  src/utils.rs
Labels: 🔧 improvement

#63 feat: split workflows
  .github/workflows/docker-build.yml
  .github/workflows/docker-publish.yml
  .github/workflows/main.yml
Labels: 🔧 improvement

#65 fix: publish action not running on pull request merge
  .github/workflows/docker-build.yml
  .github/workflows/docker.yml
Labels: 🐛 bug

#66 version: 0.2.0
  .gitignore
  Cargo.toml
  src/main.rs
Labels: :parrot: release

#67 60: Fix clippy warnings and add it to workflow
  .github/workflows/main.yml
  src/commands/genius/explain.rs
  src/commands/repeat.rs
  src/events/idle_notifier.rs
Labels: 🔧 improvement

#68 feat: auto-leave on idle
  src/commands/summon.rs
  src/events/idle_notifier.rs
  src/strings.rs
Labels: ✨ feature

#70 Update linux's `youtube-dl` installation
  README.md
Labels: ✏️ documentation

#72 #71: Version command
  src/commands/mod.rs
  src/commands/version.rs
  src/main.rs
  src/utils.rs
Labels: ✨ feature

#69 Allow prefix change
  .env.example
  .gitignore
  src/commands/mod.rs
  src/commands/prefix.rs
  src/main.rs
  src/strings.rs
  src/utils.rs
Labels: ✨ feature

#73 refactor: serenity and idle handlers in their modules & commands struct
  Cargo.toml
  src/commands/summon.rs
  src/events/idle_handler.rs
  src/events/mod.rs
  src/events/serenity_handler.rs
  src/main.rs
Labels: 🔧 improvement

#74 fix: bot activity using configured prefix
  src/events/serenity_handler.rs
  src/main.rs
  src/strings.rs
Labels: 🔧 improvement

#75 test: util module tests
  src/tests/utils.rs
  src/utils.rs
Labels: :test_tube: testing

#77 refactor: transfer main binary to lib code
  Cargo.toml
  Dockerfile
  src/client.rs
  src/lib.rs
  src/main.rs
Labels: 🔧 improvement

#78 Update Cargo.toml
  Cargo.toml
Labels: 🐛 bug

#81 fix: docker build
  Cargo.toml
  Dockerfile
  src/main.rs
Labels: 🐛 bug

#85 feat: add docker prune to docker workflow
  .github/workflows/docker.yml
Labels: 🐛 bug

#91 fix: switched `docker ps` flag
  .github/workflows/docker.yml
  Cargo.toml
Labels: 🐛 bug

#95 remove command UX enhancement
  src/commands/remove.rs
  src/events/serenity_handler.rs
Labels: 🔧 improvement

#98 #42: Command `/autopause`
  src/client.rs
  src/commands/autopause.rs
  src/commands/mod.rs
  src/commands/summon.rs
  src/events/mod.rs
  src/handlers/idle.rs
  src/handlers/mod.rs
  src/handlers/serenity.rs
  src/handlers/track_end.rs
  src/lib.rs
  src/settings.rs
Labels: ✨ feature

#99 embeds & message refactor and tweaks
  src/commands/autopause.rs
  src/commands/clear.rs
  src/commands/leave.rs
  src/commands/now_playing.rs
  src/commands/pause.rs
  src/commands/play.rs
  src/commands/queue.rs
  src/commands/remove.rs
  src/commands/repeat.rs
  src/commands/resume.rs
  src/commands/seek.rs
  src/commands/shuffle.rs
  src/commands/skip.rs
  src/commands/stop.rs
  src/commands/summon.rs
  src/commands/version.rs
  src/strings.rs
  src/utils.rs
Labels: 🔧 improvement

#96 feat: live update `/queue`
  src/client.rs
  src/commands/autopause.rs
  src/commands/clear.rs
  src/commands/leave.rs
  src/commands/pause.rs
  src/commands/play.rs
  src/commands/queue.rs
  src/commands/remove.rs
  src/commands/repeat.rs
  src/commands/resume.rs
  src/commands/seek.rs
  src/commands/shuffle.rs
  src/commands/skip.rs
  src/commands/stop.rs
  src/commands/summon.rs
  src/commands/version.rs
  src/guild/cache.rs
  src/guild/mod.rs
  src/guild/settings.rs
  src/handlers/track_end.rs
  src/lib.rs
  src/strings.rs
  src/tests/utils.rs
  src/utils.rs
Labels: 🔧 improvement

#105 fix: use now playing string from `strings.rs`
  src/utils.rs
Labels: 🔧 improvement

#108 deps: lock songbird version
  Cargo.toml
Labels: 🚫 blocked, 📦 dependency

#109 feat: use built-in input parsing & add `cargo.lock`
  .gitignore
  Cargo.lock
  src/commands/remove.rs
  src/handlers/serenity.rs
  src/strings.rs
Labels: 🔧 improvement, 📦 dependency

#111 bump: version 1.1.0
  Cargo.lock
  Cargo.toml
Labels: :parrot: release

#113 docs: added MacOS build requirements
  README.md
Labels: ✏️ documentation, 📦 dependency

#114 build: prune unused Docker dependencies
  Dockerfile
Labels: 📦 dependency

#112 ci: Optimised CI workflows
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: 🔧 improvement

#118 fix: `/play` panic in outside channel
  src/commands/summon.rs
Labels: 🐛 bug

#115 feat: custom DJ Role for parrot commands
  src/handlers/serenity.rs
Labels: ✨ feature

#119 fix: force play on same voice channel
  src/commands/play.rs
  src/commands/summon.rs
  src/handlers/serenity.rs
  src/strings.rs
  src/utils.rs
Labels: 🐛 bug
