Repository aquelemiguel/parrot, pull requests merged in 2022-10, with the labels that each got.

#202 fix: make errors follow up messages
  src/handlers/serenity.rs
  src/sources/youtube.rs
  src/utils.rs
Labels: 🪲 bug, 🎃 hacktoberfest, hacktoberfest-accepted

#205 docs: fix broken link to Linux/MacOS section
  README.md
Labels: ✏️ documentation

#206 bump: serenity to 0.11.5
  Cargo.lock
  Cargo.toml
Labels: 🎃 hacktoberfest, 📦 dependency, hacktoberfest-accepted

#204 fix: address error logging regression
  src/handlers/serenity.rs
  src/utils.rs
Labels: 🪲 bug, hacktoberfest-accepted

#208 fix: `/superplay next` with an empty queue throws ParrotError::NotInRange
  src/commands/play.rs
Labels: 🐛 bug, hacktoberfest-accepted
