Repository aquelemiguel/parrot, pull requests merged in 2022-11, with the labels that each got.

#212 chore: deprecate docker deployment workflow
  .github/workflows/docker.yml
Labels: 🔧 improvement

#216 docs: small readme improvements
  README.md
Labels: ✏️ documentation

#215 ci: implement usage of stepped workflow
  .github/workflows/build.yml
  .github/workflows/ci_workflow.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
Labels: 🔧 improvement

#219 feat: add bump action
  .github/workflows/bump.yml
Labels: ✨ feature, 📦 dependency

#221 feat: add bump action
  .github/workflows/bump.yml
Labels: 🐛 bug

#223 feat: allow streaming from other yt-dlp supported sources
  Cargo.lock
  Cargo.toml
  src/commands/manage_sources.rs
  src/commands/mod.rs
  src/commands/play.rs
  src/guild/settings.rs
  src/handlers/serenity.rs
  src/messaging/message.rs
  src/messaging/messages.rs
  src/utils.rs
Labels: ✨ feature
