Repository aquelemiguel/parrot, pull requests merged in 2022-03, with the labels that each got.

#165 fix: unresponsiveness with long songs
  src/sources/youtube.rs
Labels: 🪲 bug

#167 bump: `v1.3.1`
  Cargo.lock
  Cargo.toml
Labels: :parrot: release

#166 feat: better error handling
  .github/workflows/main.yml
  Cargo.lock
  src/commands/autopause.rs
  src/commands/clear.rs
  src/commands/leave.rs
  src/commands/now_playing.rs
  src/commands/pause.rs
  src/commands/play.rs
  src/commands/queue.rs
  src/commands/remove.rs
  src/commands/repeat.rs
  src/commands/resume.rs
  src/commands/seek.rs
  src/commands/shuffle.rs
  src/commands/skip.rs
  src/commands/stop.rs
  src/commands/summon.rs
  src/commands/version.rs
  src/commands/voteskip.rs
  src/connection.rs
  src/errors.rs
  src/handlers/serenity.rs
  src/lib.rs
  src/strings.rs
  src/utils.rs
Labels: 🔧 improvement

#169 refactor: improve verify
  src/commands/seek.rs
  src/errors.rs
  src/lib.rs
  src/test/errors.rs
  src/test/mod.rs
  src/test/utils.rs
  src/tests/mod.rs
Labels: 🧼 refactor

#168 feat: Spotify support
  .env.example
  Cargo.lock
  Cargo.toml
  Dockerfile
  README.md
  src/client.rs
  src/commands/play.rs
  src/errors.rs
  src/handlers/serenity.rs
  src/sources/mod.rs
  src/sources/spotify.rs
  src/sources/youtube.rs
  src/strings.rs
Labels: ✨ feature

#174 fix: `self_deafen`'s `get_current_user`
  src/handlers/serenity.rs
Labels: 🪲 bug

#176 fix: idle disconnect based on top track status
  src/handlers/idle.rs
Labels: 🪲 bug

#175 chore: implement issue form templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/story.yml
  .github/ISSUE_TEMPLATE/user_story.md
Labels: ✏️ documentation, 🔧 improvement

#179 chore: update dependencies
  Cargo.lock
  Cargo.toml
Labels: 📦 dependency

#177 docs: add dependency badge
  README.md
Labels: ✏️ documentation

#178 fix: clear queue after disconnect
  src/commands/clear.rs
  src/commands/play.rs
  src/commands/remove.rs
  src/commands/shuffle.rs
  src/commands/skip.rs
  src/commands/stop.rs
  src/commands/voteskip.rs
  src/handlers/idle.rs
  src/handlers/serenity.rs
  src/handlers/track_end.rs
Labels: 🪲 bug, 🧼 refactor

#184 fix: unexpected idle disconnects
  src/commands/play.rs
  src/handlers/idle.rs
Labels: 🪲 bug, 🧼 refactor

#185 bump: v1.4.0
  Cargo.lock
  Cargo.toml
Labels: :parrot: release
