Repository aquelemiguel/parrot, pull requests merged in 2022-02, with the labels that each got.

#127 feat: add `forceskip` and voting system to `skip`
  src/commands/forceskip.rs
  src/commands/mod.rs
  src/commands/skip.rs
  src/guild/cache.rs
  src/handlers/serenity.rs
  src/handlers/track_end.rs
  src/strings.rs
Labels: ✨ feature, :moneybag: high-priority

#128 bump: `v1.2.0`
  Cargo.lock
  Cargo.toml
Labels: 📦 dependency

#130 fix: `queue` & `np` check
  Cargo.lock
  Cargo.toml
  src/handlers/serenity.rs
Labels: 🐛 bug

#132 fix: better env loading error message
  README.md
  src/client.rs
Labels: 🐛 bug

#134 fix: panic on Option unwrap in `skip.rs`
  src/commands/queue.rs
  src/commands/skip.rs
  src/handlers/track_end.rs
Labels: 🐛 bug

#137 fix: `skip` accounting users connected to guild
  src/commands/skip.rs
Labels: 🐛 bug

#135 refactor: custom Restartables for unique sources
  src/commands/play.rs
  src/lib.rs
  src/sources/ffmpeg.rs
  src/sources/mod.rs
  src/sources/youtube.rs
Labels: 🔧 improvement

#140 feat: `/play` subcommands (next, all, reverse, shuffle)
  src/commands/mod.rs
  src/commands/play.rs
  src/commands/playtop.rs
  src/handlers/serenity.rs
  src/sources/youtube.rs
Labels: ✨ feature

#144 feat: play jump subcommand
  src/commands/mod.rs
  src/commands/play.rs
  src/handlers/serenity.rs
  src/sources/youtube.rs
  src/strings.rs
Labels: ✨ feature, 🔧 improvement

#143 fix: queue messages not live updating with playlist enqueue
  src/commands/play.rs
Labels: 🐛 bug, 🐤 good first issue

#152 chore: moved `PlayMode` and `QueryType` to `play`
  src/commands/mod.rs
  src/commands/play.rs
  src/sources/youtube.rs
Labels: 🔧 improvement

#150 fix: enqueue playlists
  src/commands/play.rs
Labels: 🐛 bug

#156 fix: revert audio format back to `webm[abr>0]/bestaudio/best`
  src/sources/youtube.rs
Labels: 🐛 bug

#157 improve: `play` perms & responsibility splitting
  src/commands/play.rs
  src/handlers/serenity.rs
Labels: 🔧 improvement

#160 feat: remove range of tracks
  src/commands/remove.rs
  src/handlers/serenity.rs
  src/strings.rs
Labels: ✨ feature

#161 refactor: superplay logic
  src/commands/play.rs
Labels: 🪲 bug, 🧼 refactor

#162 fix: clippy for rust `1.59.0`
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  src/commands/seek.rs
  src/sources/youtube.rs
Labels: 📦 dependency

#164 fix: hidden songs not enqueued
  src/commands/play.rs
Labels: 🪲 bug
