Repository aquelemiguel/parrot, pull requests merged in 2022-04, with the labels that each got.

#189 fix: leaving channel alongside other users
  src/handlers/serenity.rs
Labels: 🪲 bug

#190 bump: `v1.4.1`
  Cargo.lock
  Cargo.toml
Labels: 📦 dependency

#194 fix: handle age restricted videos
  src/commands/play.rs
  src/errors.rs
  src/strings.rs
Labels: 🪲 bug

#195 bump: `v1.4.2`
  Cargo.lock
  Cargo.toml
Labels: :parrot: release
